# Generated by Django 4.0 on 2023-09-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuserprofile',
            name='cellphone',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='wechatuserprofile',
            name='openid',
            field=models.CharField(max_length=255, unique=True, verbose_name='openid'),
        ),
    ]
