# Generated by Django 4.0 on 2023-09-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_alter_wechatuserprofile_cellphone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wechatuserprofile',
            unique_together={('openid', 'cellphone')},
        ),
    ]
