# Generated by Django 4.0 on 2023-09-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_alter_wechatuserprofile_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuserprofile',
            name='cellphone',
            field=models.CharField(default='', max_length=11, verbose_name='手机号码'),
        ),
    ]
