# Generated by Django 4.0 on 2023-09-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_alter_wechatuserprofile_cellphone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wechatuserprofile',
            unique_together=set(),
        ),
    ]
